### ISSUE TITLE
DS18B20 Error

### ISSUE THREAD

**Issue by jgrabitzky** [wolwin/WW-mySHP#1]
Hallo wolwin

Ich habe mit Hilfe deiner Platine HB-UNI-SENS-X den HB-UNI-Sen-CAP-MOIST aufgebaut und dementsprechend bestückt. Leider bekomme ich immer einen Error des DS1820B. Ich habe es in der 3 Volt Variante aufgebaut und bekomme es auch angelernt. Nur der Temperatursensor funktioniert nicht. 

Vieleicht eine Idee?

Danke

**Comment by wolwin** [comment]
> Ich habe mit Hilfe deiner Platine HB-UNI-SENS-X den HB-UNI-Sen-CAP-MOIST aufgebaut und dementsprechend bestückt. Leider bekomme ich immer einen Error des DS1820B. Ich habe es in der 3 Volt Variante aufgebaut und bekomme es auch angelernt. Nur der Temperatursensor funktioniert nicht.

Hallo,
wo bekommst Du einen Fehler - auf der Arduino- oder der Homematic-Seite?

Beim seriellen Arduino-Debug-Log wird verifiziert, ob ein DS18B20 vorhanden ist - dort zuerst nachsehen. Auf der Homematic-Seite muss das Addon von Jerome installiert sein ...

**Comment by jgrabitzky** [comment]
Den Fehler bekomme ich auf der Arduino Seite. Wie gesagt, ich habe die Komponenten die bei Spannungen über 3 Volt nötig sind nicht auf der Platine bestückt. 
Jetzt habe ich noch mal gemessen und am DS18B20 habe ich kein GND. Probeweise habe ich mal GND überbrückt und dann wird der Sensor auch beim Starten erkannt und liefert in der UI Werte. Anbei mal ein Foto.
![IMG_0162](https://user-images.githubusercontent.com/9860555/117925319-5a80f880-b2f7-11eb-94a5-bde8f87d6610.jpeg)

**Comment by wolwin** [comment]
> Wie gesagt, ich habe die Komponenten die bei Spannungen über 3 Volt nötig sind nicht auf der Platine bestückt.
> Jetzt habe ich noch mal gemessen und am DS18B20 habe ich kein GND. Probeweise habe ich mal GND überbrückt und dann wird der Sensor auch beim Starten erkannt und liefert in der UI Werte. Anbei mal ein Foto.

Du hast den Aufbau nicht nach Anleitung vorgenommen !! Die Spannungsregelung (LDO) ist nicht optional - sie dient dazu VERGLEICHBARE Messergebnisse des Feuchtigkeitsmessers zu garantieren - andernfalls werden bei sinkender (Batterie-) Spannung falsche Werte übermittelt. Weiter hast Du Q1 nicht bestückt und die Lötbrücke bei J2 (unten) ist nicht gesetzt. Über diese beiden Dinge wird die Masse für den DS18B20 vom Arduino aus geschaltet. Damit wird sichergestellt, dass immer nur zur Messzeit der DS18B20 als Verbraucher anliegt - Hintergrund: es gibt verschiedene DS18B20 Typen, die nicht automatisch in den Schlafmodus fallen ...

Wenn Du Deinen Aufbau durch Nachbestückung korrigiert hast, wird alles laufen wie gewünscht ...

Ich schließe damit diesen Thread als gelöst.
