### ISSUE TITLE
Naming convention of devices

### ISSUE THREAD

**Issue by Flieger37** [wolwin/WW-mySHP#3]
Hi,

I am struggling with the installation. All variables exist and have been filled with the initial values. But all other values stay at 0 for hours.

I am not sure about the naming of the sensor. In my case I changed it to "**Hausanschluss_ZS-Gas**" as I understood from your code that it has to end on "_ZS-Gas" if it is a gas sensor.

But may be I misunderstood the documentation and it has to be named "**HM-ES-TX-WM_ZS-Gas**" for the scripts to run correctly?

Parallel to your solution, the adaption of Michael Hansen is running on my RaspberrMatic and the values are updated correctly.

Regards
Martin

**Comment by Flieger37** [comment]
After checking the code again, I found the mistake:

In Line 61 to 63 you explain:
061 ! Beispiel 1: "XXXXX_ZS-Gas" oder "XXXXXX_ZS-WasserG" mit '**namesSep="_ZS-"**' als Trenner
062  ....
063  string **nameSep = "ZS-"**;

By mistake I used the string from your example in line 61 in line 63 with a leading underscore. But it only runs in the original version without the leading underscore. 

So I would suggest, to change the example in line 61 to the correct string in line 63.

That means, that line 61 should look like this:
061 ! Beispiel 1: "XXXXX_ZS-Gas" oder "XXXXXX_ZS-WasserG" mit '**namesSep="ZS-"**' als Trenner

(If I am wrong, please correct me.)

Kind regards and a big thank you for your script.

b.t.w.:
I am just waiting for the new ELV " Homematic IP Schnittst. Smart Meter HmIP-ESI-IEC" and can't wait to see, if it is running with your script to count the power values.

**Comment by wolwin** [comment]
If you change the ' nameSep' string in 'Uni-Zaehler.hsm' you have to change this in all addon hms scripts, too! Please note this, if you have created the system variables with 'Uni-Zaehler_SysCreate.hms' before!

**Comment by Flieger37** [comment]
Dear Wolfram,

thanks for your quick answer. That's also what I understood (and you have stated in the script that one should not change things below the marked line). So it was my mistake...

I accidentally changed the value in line 63, recognized my error and changed it back to the example value in line 61.

But line 61 has a leading underscore in 'namesSep="_ZS-"' before "ZS" and should look line this: 'namesSep="ZS-"' - just a little error in the example I think.

That doesn't mean to sound pedantic, it just happened to lead me to the self-inflicted mistake mentioned above.

Thanks again for your great work, which I appreciate very much!

**Comment by wolwin** [comment]
Ok - you are right - the explanation may be misleading ... I'll keep it in mind to change ... but thats development: first i've had '\_ZS-' as 'nameSep' installed - and then I wish to have the names of my system variables in a selected order. I added the 'preSysVar' with 'sys_' as default. But the result was an double underscore (not really fine) ... so I changed the 'nameSep' to 'ZS-' ... _and didn't change the comments_ ...
